# Generated by Django 4.2 on 2023-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Название товара'),
        ),
    ]
